### PR TITLE
 New design for IOBIO Homepage

### PR DESCRIPTION
**Pull request by adityaekawade**

### CODE REVIEW

**Comment by chmille4** [comment]
Hi Adit, have Tony and Gabor signed off on this?

**Comment by adityaekawade** [comment]
Hi @chmille4,
Tony and Gabor are content with the design. I am adding the finishing touches. This should be ready to launch next week!

**Comment by chmille4** [comment]
Ok, let me know when you are ready to launch. Merging will automatically update the production website.

**Comment by adityaekawade** [comment]
Sure. Thank you!

**Pull request merged**
